<a href="https://colab.research.google.com/github/anismehmahi/pytorch/blob/main/tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
my_tensor= torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)

In [9]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
my_tensor.ndim

2

In [14]:
my_tensor.shape

torch.Size([2, 3])

In [10]:
my_tensor.dtype

torch.float32

In [11]:
my_tensor.device

device(type='cpu')

In [15]:
empty = torch.empty(size=(3,4))
empty

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
rand = torch.rand(size=(3,4))
rand

tensor([[0.2003, 0.8155, 0.7421, 0.6017],
        [0.8936, 0.8324, 0.2451, 0.7355],
        [0.6330, 0.6197, 0.8995, 0.4869]])

In [18]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
eye = torch.eye(3,4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [28]:
arange = torch.arange(start=0, end=5, step=2)
arange

tensor([0, 2, 4])

In [27]:
lisnpace = torch.linspace(start=0, end=5, steps=10)
lisnpace

tensor([0.0000, 0.5556, 1.1111, 1.6667, 2.2222, 2.7778, 3.3333, 3.8889, 4.4444,
        5.0000])

In [31]:
normal_tensor = torch.empty(size=(2,4)).normal_(0,1)
normal_tensor

tensor([[-1.1609, -0.6145, -0.1457,  0.5694],
        [-1.0018,  1.3522, -0.0512,  1.0237]])

In [34]:
normal_tensor.mean(axis=0)

tensor([-1.0814,  0.3689, -0.0985,  0.7965])

In [35]:
normal_tensor.mean(axis=1)

tensor([-0.3379,  0.3307])

In [36]:
normal_tensor.mean(axis=-1)

tensor([-0.3379,  0.3307])

In [41]:
torch.arange(4).short() # to int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [43]:
torch.arange(4).long() # to int64 (Important)

tensor([0, 1, 2, 3])

In [42]:
torch.arange(4).half() # to float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [46]:
torch.arange(4).float() # to float32 (Important)

tensor([0., 1., 2., 3.])

In [47]:
torch.arange(4).double() # to float64

tensor([0., 1., 2., 3.], dtype=torch.float64)

## Math Operations

In [49]:
x = torch.rand((1,3))
x

tensor([[0.7142, 0.3094, 0.3238]])

In [52]:
y = torch.rand(1,3)
y

tensor([[0.2482, 0.8144, 0.3288]])

In [53]:
x+y

tensor([[0.9624, 1.1237, 0.6525]])

In [54]:
x-y

tensor([[ 0.4660, -0.5050, -0.0050]])

In [55]:
x*y

tensor([[0.1773, 0.2519, 0.1064]])

In [57]:
x@y.T

tensor([[0.5356]])

In [58]:
x/y

tensor([[2.8776, 0.3799, 0.9848]])

In [60]:
x**2

tensor([[0.5101, 0.0957, 0.1048]])

In [61]:
x==y

tensor([[False, False, False]])

In [62]:
x>0

tensor([[True, True, True]])

In [64]:
x1 = torch.rand(2,5)
x2= torch.rand(5,3)

In [66]:
x1.mm(x2)

tensor([[1.0582, 1.0139, 0.8393],
        [1.4272, 1.5501, 1.5893]])

In [69]:
x1

tensor([[0.6167, 0.3767, 0.6945, 0.1146, 0.1363],
        [0.4315, 0.9471, 0.0514, 0.6386, 0.0523]])

In [72]:
x1**3 # element wise à la puissance 3

tensor([[2.3454e-01, 5.3450e-02, 3.3496e-01, 1.5042e-03, 2.5314e-03],
        [8.0335e-02, 8.4947e-01, 1.3597e-04, 2.6037e-01, 1.4326e-04]])

In [73]:
x1.matrix_power(3) # this one do matrix @ matrix @ matrix but matrix should be square

RuntimeError: linalg.matrix_power: A must be batches of square matrices, but they are 2 by 5 matrices

In [80]:
y.squeeze().shape

torch.Size([3])

In [81]:
torch.dot(x.squeeze(),y.squeeze()) # dot product only for vectors (1D)

tensor(0.5356)

In [83]:
torch.mm(x,y.T)

tensor([[0.5356]])

In [ ]:
# Batch Matrix Multiplication
batch = 32
n=3
m=4
p=2
tensor1 = torch.rand(batch,n,m)
tensor2=torch.rand(batch,m,p)

# this will matrix multiply the first matrix from the first batch with the forst matrix from the second batch
batch_mult = torch.bmm(tensor1,tensor2)
batch_mult

In [87]:
batch_mult.shape

torch.Size([32, 3, 2])

In [91]:
tensor1[0].mm(tensor2[0])

tensor([[0.9855, 0.9525],
        [1.0360, 1.0017],
        [1.0346, 0.9781]])

In [92]:
batch_mult[0]

tensor([[0.9855, 0.9525],
        [1.0360, 1.0017],
        [1.0346, 0.9781]])

## Broadcasting

In [99]:
a1 = torch.rand(3,5)
a2 = torch.rand(1,5)

In [106]:
a1-a2

tensor([[-0.0598,  0.5742,  0.4843, -0.3402, -0.1638],
        [-0.0263, -0.0989,  0.0413, -0.2737, -0.1322],
        [ 0.2537,  0.1082, -0.2547,  0.0499,  0.3471]])

In [105]:
a1

tensor([[0.2034, 0.9386, 0.9440, 0.5779, 0.4068],
        [0.2370, 0.2655, 0.5010, 0.6445, 0.4384],
        [0.5169, 0.4726, 0.2050, 0.9680, 0.9177]])

In [107]:
a1.sum(dim=0)

tensor([0.9573, 1.6767, 1.6499, 2.1904, 1.7628])

In [108]:
a1.max(dim=0)

torch.return_types.max(
values=tensor([0.5169, 0.9386, 0.9440, 0.9680, 0.9177]),
indices=tensor([2, 0, 0, 2, 2]))

In [131]:
batch_ma = torch.rand(4,3,2)
result = batch_ma.max(dim=0)
result

In [135]:
batch_ma.sum(dim=0)

tensor([[1.6414, 2.2400],
        [2.0727, 0.6145],
        [1.7152, 2.5901]])

In [125]:
result[0].shape

torch.Size([3, 2])

In [137]:
batch_ma

tensor([[[0.0567, 0.7254],
         [0.3593, 0.2397],
         [0.3305, 0.4140]],

        [[0.3479, 0.6250],
         [0.8657, 0.1172],
         [0.4814, 0.7503]],

        [[0.8206, 0.3425],
         [0.2304, 0.1928],
         [0.6111, 0.5644]],

        [[0.4163, 0.5470],
         [0.6173, 0.0648],
         [0.2922, 0.8613]]])

In [136]:
batch_ma.mean(dim=1)

tensor([[0.2488, 0.4597],
        [0.5650, 0.4975],
        [0.5540, 0.3666],
        [0.4419, 0.4911]])

In [142]:
batch_ma.sort(dim=0)

torch.return_types.sort(
values=tensor([[[0.0567, 0.3425],
         [0.2304, 0.0648],
         [0.2922, 0.4140]],

        [[0.3479, 0.5470],
         [0.3593, 0.1172],
         [0.3305, 0.5644]],

        [[0.4163, 0.6250],
         [0.6173, 0.1928],
         [0.4814, 0.7503]],

        [[0.8206, 0.7254],
         [0.8657, 0.2397],
         [0.6111, 0.8613]]]),
indices=tensor([[[0, 2],
         [2, 3],
         [3, 0]],

        [[1, 3],
         [0, 1],
         [0, 2]],

        [[3, 1],
         [3, 2],
         [1, 1]],

        [[2, 0],
         [1, 0],
         [2, 3]]]))

In [143]:
torch.clamp(batch_ma,min=10)

tensor([[[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]]])

In [145]:
torch.all(batch_ma)

tensor(True)

## Indexing

In [146]:
data= torch.rand(50,5)

In [150]:
data

tensor([[7.8366e-01, 9.1310e-01, 6.6921e-01, 7.7524e-01, 6.1098e-01],
        [2.2234e-01, 4.0959e-02, 6.3398e-01, 3.0789e-01, 1.9760e-01],
        [5.1415e-01, 6.4699e-01, 2.7465e-01, 6.6093e-01, 8.3874e-01],
        [8.5191e-01, 6.8952e-01, 5.2789e-01, 6.6804e-01, 2.2931e-01],
        [7.1780e-01, 2.3846e-01, 2.9103e-01, 2.8260e-01, 6.0232e-02],
        [3.0650e-01, 5.7740e-01, 4.5282e-01, 5.0954e-01, 3.1197e-01],
        [5.2344e-01, 5.3447e-02, 8.1367e-01, 8.6995e-01, 3.9357e-01],
        [6.6294e-01, 8.3795e-01, 4.3209e-01, 1.0471e-01, 3.5565e-01],
        [6.9180e-01, 7.7120e-02, 9.6411e-01, 1.7223e-02, 1.7230e-01],
        [3.7471e-01, 1.2729e-01, 7.9218e-01, 2.7884e-01, 9.3530e-01],
        [2.8356e-01, 8.7288e-01, 1.6124e-01, 1.6178e-01, 2.3027e-01],
        [8.5472e-01, 6.0423e-01, 5.5170e-01, 4.8241e-01, 1.3729e-01],
        [6.3864e-01, 9.3750e-01, 1.0122e-02, 2.3067e-01, 7.5305e-01],
        [4.6593e-02, 1.4891e-01, 4.8666e-01, 1.2118e-01, 9.9791e-02],
        [4.0179e-01,

In [148]:
data[3,:]

tensor([0.8519, 0.6895, 0.5279, 0.6680, 0.2293])

In [149]:
data[:,0]

tensor([0.7837, 0.2223, 0.5141, 0.8519, 0.7178, 0.3065, 0.5234, 0.6629, 0.6918,
        0.3747, 0.2836, 0.8547, 0.6386, 0.0466, 0.4018, 0.4152, 0.1116, 0.0600,
        0.6743, 0.3109, 0.4280, 0.4484, 0.3747, 0.8543, 0.9953, 0.3321, 0.5820,
        0.9445, 0.5520, 0.6038, 0.8199, 0.1682, 0.4655, 0.3381, 0.0213, 0.4524,
        0.7284, 0.2948, 0.9882, 0.8848, 0.4215, 0.4453, 0.2535, 0.9389, 0.9753,
        0.6889, 0.2880, 0.9235, 0.6052, 0.4599])

In [151]:
data[[2,3,4]]

tensor([[0.5141, 0.6470, 0.2747, 0.6609, 0.8387],
        [0.8519, 0.6895, 0.5279, 0.6680, 0.2293],
        [0.7178, 0.2385, 0.2910, 0.2826, 0.0602]])

In [153]:
data[[2,3,4],[0,1,2]]

tensor([0.5141, 0.6895, 0.2910])

In [155]:
data[0:3,0:8]

tensor([[0.7837, 0.9131, 0.6692, 0.7752, 0.6110],
        [0.2223, 0.0410, 0.6340, 0.3079, 0.1976],
        [0.5141, 0.6470, 0.2747, 0.6609, 0.8387]])

In [158]:
first_column = data[:,0]
first_column[first_column>0.2]

tensor([0.7837, 0.2223, 0.5141, 0.8519, 0.7178, 0.3065, 0.5234, 0.6629, 0.6918,
        0.3747, 0.2836, 0.8547, 0.6386, 0.4018, 0.4152, 0.6743, 0.3109, 0.4280,
        0.4484, 0.3747, 0.8543, 0.9953, 0.3321, 0.5820, 0.9445, 0.5520, 0.6038,
        0.8199, 0.4655, 0.3381, 0.4524, 0.7284, 0.2948, 0.9882, 0.8848, 0.4215,
        0.4453, 0.2535, 0.9389, 0.9753, 0.6889, 0.2880, 0.9235, 0.6052, 0.4599])

In [171]:
torch.where(data>0.6, data, -99)

tensor([[  0.7837,   0.9131,   0.6692,   0.7752,   0.6110],
        [-99.0000, -99.0000,   0.6340, -99.0000, -99.0000],
        [-99.0000,   0.6470, -99.0000,   0.6609,   0.8387],
        [  0.8519,   0.6895, -99.0000,   0.6680, -99.0000],
        [  0.7178, -99.0000, -99.0000, -99.0000, -99.0000],
        [-99.0000, -99.0000, -99.0000, -99.0000, -99.0000],
        [-99.0000, -99.0000,   0.8137,   0.8699, -99.0000],
        [  0.6629,   0.8380, -99.0000, -99.0000, -99.0000],
        [  0.6918, -99.0000,   0.9641, -99.0000, -99.0000],
        [-99.0000, -99.0000,   0.7922, -99.0000,   0.9353],
        [-99.0000,   0.8729, -99.0000, -99.0000, -99.0000],
        [  0.8547,   0.6042, -99.0000, -99.0000, -99.0000],
        [  0.6386,   0.9375, -99.0000, -99.0000,   0.7530],
        [-99.0000, -99.0000, -99.0000, -99.0000, -99.0000],
        [-99.0000, -99.0000,   0.8363,   0.9643, -99.0000],
        [-99.0000,   0.7424,   0.6176, -99.0000, -99.0000],
        [-99.0000,   0.6335,   0.8771, -

In [169]:
data

tensor([[7.8366e-01, 9.1310e-01, 6.6921e-01, 7.7524e-01, 6.1098e-01],
        [2.2234e-01, 4.0959e-02, 6.3398e-01, 3.0789e-01, 1.9760e-01],
        [5.1415e-01, 6.4699e-01, 2.7465e-01, 6.6093e-01, 8.3874e-01],
        [8.5191e-01, 6.8952e-01, 5.2789e-01, 6.6804e-01, 2.2931e-01],
        [7.1780e-01, 2.3846e-01, 2.9103e-01, 2.8260e-01, 6.0232e-02],
        [3.0650e-01, 5.7740e-01, 4.5282e-01, 5.0954e-01, 3.1197e-01],
        [5.2344e-01, 5.3447e-02, 8.1367e-01, 8.6995e-01, 3.9357e-01],
        [6.6294e-01, 8.3795e-01, 4.3209e-01, 1.0471e-01, 3.5565e-01],
        [6.9180e-01, 7.7120e-02, 9.6411e-01, 1.7223e-02, 1.7230e-01],
        [3.7471e-01, 1.2729e-01, 7.9218e-01, 2.7884e-01, 9.3530e-01],
        [2.8356e-01, 8.7288e-01, 1.6124e-01, 1.6178e-01, 2.3027e-01],
        [8.5472e-01, 6.0423e-01, 5.5170e-01, 4.8241e-01, 1.3729e-01],
        [6.3864e-01, 9.3750e-01, 1.0122e-02, 2.3067e-01, 7.5305e-01],
        [4.6593e-02, 1.4891e-01, 4.8666e-01, 1.2118e-01, 9.9791e-02],
        [4.0179e-01,

## Reshaping

In [173]:
# they do the samething so what is the diff ????
data.view(25,10)
data.reshape(25,10) # use this allways

tensor([[7.8366e-01, 9.1310e-01, 6.6921e-01, 7.7524e-01, 6.1098e-01, 2.2234e-01,
         4.0959e-02, 6.3398e-01, 3.0789e-01, 1.9760e-01],
        [5.1415e-01, 6.4699e-01, 2.7465e-01, 6.6093e-01, 8.3874e-01, 8.5191e-01,
         6.8952e-01, 5.2789e-01, 6.6804e-01, 2.2931e-01],
        [7.1780e-01, 2.3846e-01, 2.9103e-01, 2.8260e-01, 6.0232e-02, 3.0650e-01,
         5.7740e-01, 4.5282e-01, 5.0954e-01, 3.1197e-01],
        [5.2344e-01, 5.3447e-02, 8.1367e-01, 8.6995e-01, 3.9357e-01, 6.6294e-01,
         8.3795e-01, 4.3209e-01, 1.0471e-01, 3.5565e-01],
        [6.9180e-01, 7.7120e-02, 9.6411e-01, 1.7223e-02, 1.7230e-01, 3.7471e-01,
         1.2729e-01, 7.9218e-01, 2.7884e-01, 9.3530e-01],
        [2.8356e-01, 8.7288e-01, 1.6124e-01, 1.6178e-01, 2.3027e-01, 8.5472e-01,
         6.0423e-01, 5.5170e-01, 4.8241e-01, 1.3729e-01],
        [6.3864e-01, 9.3750e-01, 1.0122e-02, 2.3067e-01, 7.5305e-01, 4.6593e-02,
         1.4891e-01, 4.8666e-01, 1.2118e-01, 9.9791e-02],
        [4.0179e-01, 2.2029

In [187]:
one = torch.rand((3,4))
one

tensor([[0.2101, 0.6435, 0.0388, 0.8100],
        [0.1812, 0.3937, 0.4434, 0.1169],
        [0.3914, 0.4114, 0.7601, 0.5233]])

In [188]:
two = torch.rand(3,4)
two

tensor([[0.4420, 0.5453, 0.6664, 0.1937],
        [0.9433, 0.3839, 0.9237, 0.3278],
        [0.5156, 0.5111, 0.2954, 0.7810]])

In [194]:
cat = torch.cat((one,two),axis=1 )
print('shape = ', cat.shape)
print(cat)

shape =  torch.Size([3, 8])
tensor([[0.2101, 0.6435, 0.0388, 0.8100, 0.4420, 0.5453, 0.6664, 0.1937],
        [0.1812, 0.3937, 0.4434, 0.1169, 0.9433, 0.3839, 0.9237, 0.3278],
        [0.3914, 0.4114, 0.7601, 0.5233, 0.5156, 0.5111, 0.2954, 0.7810]])


In [195]:
cat.view(-1) # flatten

tensor([0.2101, 0.6435, 0.0388, 0.8100, 0.4420, 0.5453, 0.6664, 0.1937, 0.1812,
        0.3937, 0.4434, 0.1169, 0.9433, 0.3839, 0.9237, 0.3278, 0.3914, 0.4114,
        0.7601, 0.5233, 0.5156, 0.5111, 0.2954, 0.7810])

In [196]:
batch=64
z = torch.rand(batch,3,4)
cc = z.view(batch,-1)
cc.shape

torch.Size([64, 12])

In [197]:
z.shape

torch.Size([64, 3, 4])

In [200]:
permuted_z = z.permute(0,2,1)
permuted_z.shape

torch.Size([64, 4, 3])

In [202]:
z

tensor([[[5.5513e-02, 7.6243e-01, 3.0147e-01, 7.9189e-01],
         [9.5505e-01, 7.6108e-01, 9.9913e-01, 6.4406e-01],
         [8.0851e-01, 1.7901e-02, 7.8351e-01, 1.3741e-01]],

        [[8.4228e-01, 3.2384e-01, 2.7464e-02, 3.6219e-01],
         [8.0195e-02, 2.3335e-01, 6.7690e-01, 2.3691e-01],
         [3.3120e-01, 6.9655e-01, 7.4720e-01, 6.3071e-01]],

        [[4.9614e-01, 2.9107e-01, 3.5163e-01, 2.6293e-01],
         [6.1749e-01, 6.7390e-01, 4.1087e-01, 1.1985e-01],
         [3.9350e-01, 9.7212e-01, 6.2843e-02, 8.4783e-01]],

        [[5.8432e-01, 3.4096e-02, 6.9040e-01, 9.6894e-02],
         [1.5840e-01, 8.0570e-01, 1.2484e-01, 9.9874e-01],
         [2.6486e-01, 6.7320e-01, 4.0321e-01, 2.8052e-01]],

        [[9.3793e-01, 7.2502e-01, 7.0415e-01, 8.0265e-01],
         [7.7074e-01, 1.8211e-01, 3.6432e-02, 5.5389e-01],
         [8.4656e-01, 4.5828e-01, 2.7313e-01, 4.2464e-01]],

        [[2.9667e-01, 2.4634e-01, 8.8384e-01, 2.4490e-01],
         [2.6870e-01, 5.8640e-01, 5.0125e-01, 

In [201]:
permuted_z

tensor([[[5.5513e-02, 9.5505e-01, 8.0851e-01],
         [7.6243e-01, 7.6108e-01, 1.7901e-02],
         [3.0147e-01, 9.9913e-01, 7.8351e-01],
         [7.9189e-01, 6.4406e-01, 1.3741e-01]],

        [[8.4228e-01, 8.0195e-02, 3.3120e-01],
         [3.2384e-01, 2.3335e-01, 6.9655e-01],
         [2.7464e-02, 6.7690e-01, 7.4720e-01],
         [3.6219e-01, 2.3691e-01, 6.3071e-01]],

        [[4.9614e-01, 6.1749e-01, 3.9350e-01],
         [2.9107e-01, 6.7390e-01, 9.7212e-01],
         [3.5163e-01, 4.1087e-01, 6.2843e-02],
         [2.6293e-01, 1.1985e-01, 8.4783e-01]],

        [[5.8432e-01, 1.5840e-01, 2.6486e-01],
         [3.4096e-02, 8.0570e-01, 6.7320e-01],
         [6.9040e-01, 1.2484e-01, 4.0321e-01],
         [9.6894e-02, 9.9874e-01, 2.8052e-01]],

        [[9.3793e-01, 7.7074e-01, 8.4656e-01],
         [7.2502e-01, 1.8211e-01, 4.5828e-01],
         [7.0415e-01, 3.6432e-02, 2.7313e-01],
         [8.0265e-01, 5.5389e-01, 4.2464e-01]],

        [[2.9667e-01, 2.6870e-01, 6.7494e-01],
   

In [206]:
z.unsqueeze(2).shape

torch.Size([64, 3, 1, 4])